### PR TITLE
Create mmaroun.md

### PR DESCRIPTION
**Pull request by mmaroun0**
Description for Matthew Maroun, one of the trainees for the TAC-HEP Program

### CODE REVIEW

**Comment by pelmer** [comment]
I think you need to add the photo, too

**Comment by mmaroun0** [comment]
Hi Peter,

Sorry for this confusion. I think I've attached the photo I wish to
include. Please let me know if I sent it over correctly.

Thanks again,
Matt

On Wed, Mar 29, 2023 at 12:47 PM Peter Elmer ***@***.***>
wrote:

> I think you need to add the photo, too
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftac-hep%2Ftac-hep.github.io%2Fpull%2F5%23issuecomment-1488949935&data=05%7C01%7Cmmaroun%40umass.edu%7C6866ac87296e4ca3d25a08db30754ea1%7C7bd08b0b33954dc194bbd0b2e56a497f%7C0%7C0%7C638157052617598115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gqh037%2FeGqq8Mjo9RvkuS9zyWRlhlilaO63c6aRSkeQ%3D&reserved=0>,
> or unsubscribe
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYXWJIM5OWYARKDEUUG6FP3W6RRSVANCNFSM6AAAAAAWMCLV6Y&data=05%7C01%7Cmmaroun%40umass.edu%7C6866ac87296e4ca3d25a08db30754ea1%7C7bd08b0b33954dc194bbd0b2e56a497f%7C0%7C0%7C638157052617598115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GSPiPcGnFJLj6E7cSOT2pLweD851FEM1ZSMUDNpVYzw%3D&reserved=0>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
Matthew Maroun
*Physics Graduate Student*
*University of Massachusetts, Amherst*

**Comment by pelmer** [comment]
If you look at the others, they are mostly head shots

**Comment by mmaroun0** [comment]
Unfortunately, I do not have any professional headshots available to
include for the site. Should I remove my photo?

Thanks,
Matt

On Wed, Mar 29, 2023 at 4:17 PM Peter Elmer ***@***.***>
wrote:

> If you look at the others, they are mostly head shots
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftac-hep%2Ftac-hep.github.io%2Fpull%2F5%23issuecomment-1489247101&data=05%7C01%7Cmmaroun%40umass.edu%7C4260c6efb8cc4dd7540c08db30928e3a%7C7bd08b0b33954dc194bbd0b2e56a497f%7C0%7C0%7C638157178226555446%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F42ClHKW3XYi4pL8UxRHJLp8Kt%2FuhXbooACa0IquQfw%3D&reserved=0>,
> or unsubscribe
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYXWJIJTMIEZBDJLL3C722DW6SKDZANCNFSM6AAAAAAWMCLV6Y&data=05%7C01%7Cmmaroun%40umass.edu%7C4260c6efb8cc4dd7540c08db30928e3a%7C7bd08b0b33954dc194bbd0b2e56a497f%7C0%7C0%7C638157178226555446%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Vdxvq5SSo4hX0Asox5V0JXiJ4DDeVAx0AcNXkgJ7IVk%3D&reserved=0>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
Matthew Maroun
*Physics Graduate Student*
*University of Massachusetts, Amherst*

**Comment by pelmer** [comment]
Well, that photo doesn't really look like a professional one, either... ;-) We could try to crop in on that, but the resolution is kinda low. Maybe someone could take a picture with their phone? Otherwise I can just crop in on this one. Whichever you prefer.

**Comment by mmaroun0** [comment]
Matthew-Maroun
Will this crop work?

**Comment by mmaroun0** [comment]
I believe the files are in a state to be ready to be pulled. Thanks

**Pull request merged**
